#!/bin/bash

if [ -z "$(ls ./data/*.csv 2>/dev/null)" ]; then
    echo "transfering data train, test"
    cp ../train.csv ./phase2_module/data/
    cp ../submission.csv ./phase2_module/data/test.csv
else
    echo "already data files exists"
fi
